//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace limantakip4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gemıı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gemıı()
        {
            this.Lımann = new HashSet<Lımann>();
        }
    
        public int ID { get; set; }
        public string GEMIYUK { get; set; }
        public string GEMIYUKTONU { get; set; }
        public string GEMITONAJ { get; set; }
        public string GEMIMURETTEBAT { get; set; }
        public string GEMIBAYRAK { get; set; }
        public Nullable<int> GEMIBULLIMAN { get; set; }
        public string GEMIULLIMAN { get; set; }
        public Nullable<int> GEMISIRKET { get; set; }
        public Nullable<System.DateTime> GEMICIKTARIH { get; set; }
        public Nullable<System.DateTime> GEMIVARTARIH { get; set; }
    
        public virtual Sırkett Sırkett { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lımann> Lımann { get; set; }
    }
}
