//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace limantakip4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lımann
    {
        public int ID { get; set; }
        public string LIMANAD { get; set; }
        public string LIMANSEHIR { get; set; }
        public string LIMANULKE { get; set; }
        public Nullable<int> LIMANGEMI { get; set; }
    
        public virtual Gemıı Gemıı { get; set; }
    }
}
