//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace limantakip4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uye
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Kullanıcı bilgisi girilmelidir")]
        public string kullanıcıadı { get; set; }
        [Required(ErrorMessage = "Password girilmelidir")]
        [DataType(DataType.Password)]
        public string sifre { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
